version: '3.9'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: user_microservice
      MYSQL_ROOT_PASSWORD: 12345

  springboot-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      #DATABASE_URL:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: 12345
      KEYSECRET_SECURITY: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.nZU_gPcMXkWpkCUpJceSxS7lSickF0tTImHhAR949Z-Nt69LgW8G6lid-mqd9B579tYM8C4FN2jdhR2VRMsjtA
      EXPIRE_DAYS_SECURITY: 3600000
    depends_on:
      - mysqldb