server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
jwt:
  secret: ${KEYSECRET_SECURITY}
  expiration: ${EXPIRE_DAYS_SECURITY}